name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: preliminary
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: cases to run
      run: |
        TESTS=$(cut -d "," -f 1 tests.txt)
        echo $TESTS

  job2:
    name: ${{ matrix.kind }} test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kind: [rst,dcp,mpi]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: step 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -l
        ./hello.sh ${{ matrix.kind }}

    - name: step 2
      run: echo "${{ matrix.kind }}"
