name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: preliminary
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.pstep1.outputs.test }}
      output2: ${{ steps.pstep2.outputs.test }}
      output3: ${{ steps.pstep3.outputs.test }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - id: pstep1
      run: |
        TEST1=$(cut -d "," -f 1 ${GITHUB_WORKSPACE}/tests.txt)
        #TESTS=$(cat ${GITHUB_WORKSPACE}/tests.txt)
        echo "::set-output name=test::${TEST1}"
        
    - id: pstep2
      run: |
        TEST2=$(cut -d "," -f 2 ${GITHUB_WORKSPACE}/tests.txt)
        echo "::set-output name=test::${TEST2}"

    - id: pstep3
      run: |
        TEST3=$(cut -d "," -f 3 ${GITHUB_WORKSPACE}/tests.txt)
        echo "::set-output name=test::${TEST3}"

  job2:
    name: ${{ matrix.kind }} test
    needs: job1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #kind: [rst]
        kind: ["${{needs.job1.outputs.output1}}","${{needs.job1.outputs.output2}}","${{needs.job1.outputs.output3}}"]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: step 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -l
        ./hello.sh ${{ matrix.kind }}
        echo "${{needs.job1.outputs.output1}}"

    - name: step 2
      run: echo "${{ matrix.kind }}"
