name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: determine cases to run
    runs-on: ubuntu-latest

    outputs:
      mtx: ${{ steps.parse.outputs.m }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Parse cases
      id: parse
      run: echo "::set-output name=m::$(sed -n 2p ${GITHUB_WORKSPACE}/tests.txt)"

  job2:
    name: ${{ matrix.kind }} test
    needs: job1
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.job1.outputs.mtx)}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Step 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -l
        ./hello.sh ${{ matrix.kind }}

    - name: Step 2
      run: echo "${{ matrix.kind }}"
