name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job:
    name: ${{ matrix.kind }} test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kind: [rst,dcp,mpi]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: step 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -l
        ./hello.sh ${{ matrix.kind }}

    - name: step 2
      run: echo "${{ matrix.kind }}"
