name: test

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: ${{ matrix.kind }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: [rst,dcp,mpi]
    steps:
    - name: step 1
      run: echo "Hello, ${{ matrix.kind }}"
