name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: ${{ matrix.kind }} test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: [rst,dcp,mpi]
    steps:
    - name: step 1
      run: |
        pwd
        ls -l $(pwd)
        df -h
        #MYDIR=$(dirname $(pwd))
        #${GITHUB_WORKSPACE}/hello.sh ${{ matrix.kind }}
    - name: step 2
      run: echo "${{ matrix.kind }}"
