name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: preliminary
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: cases to run
      id: prelim_step
      run: |
        TESTS=$(cut -d "," -f 1 ${GITHUB_WORKSPACE}/tests.txt)
        echo "::set-output name=cases::${TESTS}"
        

  job2:
    name: ${{ matrix.kind }} test
    needs: job1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kind: [rst]
        #kind: [${{ jobs.job1.steps.prelim_step.outputs.cases }}]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: step 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -l
        ./hello.sh ${{ matrix.kind }}
        echo "${{ needs.job1.steps.prelim_step.outputs.cases }}"

    - name: step 2
      run: echo "${{ matrix.kind }}"
