name: Pull request tests

on:
  push:
    branches:
    - master

jobs:
  job1:
    name: preliminary
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.pstep.outputs.test1 }}
      output2: ${{ steps.pstep.outputs.test2 }}
      output3: ${{ steps.pstep.outputs.test3 }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: parse cases to run
      id: pstep
      run: |
        echo "::set-output name=test1::$(cut -d, -f1 ${GITHUB_WORKSPACE}/tests.txt)"
        echo "::set-output name=test2::$(cut -d, -f2 ${GITHUB_WORKSPACE}/tests.txt)"
        echo "::set-output name=test3::$(cut -d, -f3 ${GITHUB_WORKSPACE}/tests.txt)"
        
  job2:
    name: ${{ matrix.kind }} test
    needs: job1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kind: ["${{needs.job1.outputs.output1}}","${{needs.job1.outputs.output2}}","${{needs.job1.outputs.output3}}",,]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: step 1
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -l
        ./hello.sh ${{ matrix.kind }}

    - name: step 2
      run: echo "${{ matrix.kind }}"
